'use strict';

function cFileExtensions(){

	var self = this;
	self._types = {};
	self._mime = null;

	self._extTable = {
		'3d': [['3ds','3dm','max','obj'],'3D'],
		'adobe': [['ai','ait','indd','prproj','ppj','aep','aet'],'Adobe'],
		'archive': [['zip','rar','tgz','gz','bz2','tbz','tar','7z','sitx'],'Compressed'],
		'audio': [['mp3','wav','3ga','aif','aiff','flac','iff','m4a','wma'],'Audio'],
		'cad': [['dxf','dwg'],'CAD'],
		'db': [['sql','accdb','db','dbf','mdb','pdb','dwt'],'Database'],
		'excel': [['xls','xlsx','xlt','xltm'],'Excel'],
		'exe': [['exe','com','bin','apk','app','msi','cmd','gadget','bat'],'Executable'],
		'actionscript': [['as','ascs','asc'],'ActionScript'],
		'flash': [['fla'],'Flash'],
		'flashvideo': [['flv','swf'],'Flash Video'],
		'font': [['fnt','otf','ttf','fon','woff','eot'],'Font'],
		'gps': [['gpx','kml','kmz'],'GPS File'],
		'image': [['gif','tiff','tif','bmp','png','tga','jpg','jpeg'],'Image'],
		'java': [['jar','java','class'],'Java'],
		'midi': [['mid','midi'],'Midi'],
		'pdf': [['pdf'],'PDF'],
		'playlist': [['pls','m3u','asx'],'Playlist'],
		'podcast': [['pcast'],'Podcast'],
		'ppt': [['pps','ppt','pptx'],'Powerpoint'],
		'ps': [['abr','psb','psd'],'Adobe Photoshop'],
		'rawdata': [['3fr','arw','bay','cr2','dcr','dng','fff','mef','mrw','nef','pef','rw2','srf','orf','rwl'],'RAW'],
		'realaudio': [['rm','ra','ram'],'Real Audio'],
		'source': [['sh','c','cc','cpp','cxx','h','hpp','dll','iso'],'Source code'],
		'sheet': [['ods','ots','gsheet','nb','xlr','numbers'],'Spreadsheet'],
		'subtitle': [['srt'],'Subtitle'],
		'text': [['txt','rtf','ans','ascii','log','odt','wpd'],'Text'],
		'torrent': [['torrent'],'Torrent'],
		'vcard': [['vcf'],'Vcard'],
		'vector': [['svgz','svg','cdr','eps'],'Vector'],
		'video': [['mkv','webm','avi','mp4','m4v','mpg','mpeg','mov','3g2','3gp','asf','wmv'],'Video'],
		'html': [['html','xml','htm','xhtml','shtml','dhtml','js','css'],'Web Client Code'],
		'serverCode': [['php','php3','php4','php5','phtml','inc','asp','aspx','pl','cgi','py'],'Web Server Code'],
		'word': [['doc','docx','dotx','wps'],'MS Word'],
		'file': [['*'],'File'],
	};

	self._extWide = {
		'3ds': '3D Scene',
		'3dm': '3D Model',
		'3fr': 'RAW',
		'3g2': 'Multimedia',
		'3gp': '3D Model',
		'7z': '7-Zip Compressed',
		'accdb': 'Database',
		'aep': 'After Effects',
		'aet': 'After Effects',
		'ai': 'Illustrator',
		'aif': 'Audio Interchange',
		'aiff': 'Audio Interchange',
		'ait': 'Illustrator',
		'ans': 'ANSI Text File',
		'apk': 'Android App',
		'app': 'Mac OSX App',
		'arw': 'RAW',
		'as': 'ActionScript',
		'asc': 'ActionScript Com',
		'ascii': 'ASCII Text',
		'asf': 'Streaming Video',
		'asp': 'Active Server',
		'aspx': 'Active Server',
		'asx': 'Advanced Stream',
		'avi': 'Video',
		'bat': 'DOS Batch',
		'bay': 'Casio RAW',
		'bmp': 'Bitmap',
		'bz2': 'UNIX Compressed',
		'c': 'C/C++ Source Code',
		'cc': 'C++ Source Code',
		'cdr': 'CorelDraw',
		'cgi': 'CGI Script',
		'class': 'Java Class',
		'com': 'DOS Command',
		'cpp': 'C++ Source Code',
		'cr2': 'Raw',
		'css': 'CSS Style Sheet',
		'cxx': 'C++ Source Code',
		'dcr': 'Raw',
		'db': 'Database',
		'dbf': 'Database',
		'dhtml': 'Dynamic HTML',
		'dll': 'Dynamic Link Library',
		'dng': 'Digital Negative',
		'doc': 'MS Word',
		'docx': 'MS Word',
		'dotx': 'MS Word Template',
		'dwg': 'Drawing DB File',
		'dwt': 'Dreamweaver',
		'dxf': 'DXF',
		'eps': 'EPS',
		'exe': 'Executable',
		'fff': 'RAW',
		'fla': 'Adobe Flash',
		'flac': 'Lossless Audio',
		'flv': 'Flash Video',
		'fnt': 'Windows Font',
		'fon': 'Font',
		'gadget': 'Windows Gadget',
		'gif': 'GIF',
		'gpx': 'GPS Exchange',
		'gsheet': 'Spreadsheet',
		'gz': 'Gnu Compressed',
		'h': 'Header',
		'hpp': 'Header',
		'htm': 'HTML',
		'html': 'HTML',
		'iff': 'Interchange',
		'inc': 'Include',
		'indd': 'Adobe InDesign',
		'iso': 'ISO',
		'jar': 'Java Archive',
		'java': 'Java',
		'jpeg': 'JPEG',
		'jpg': 'JPEG',
		'js': 'JavaScript',
		'kml': 'Google Earth',
		'log': 'Log',
		'm3u': 'Media Playlist',
		'm4a': 'MPEG-4 Audio',
		'max': '3ds Max Scene',
		'mdb': 'MS Access',
		'mef': 'RAW',
		'mid': 'MIDI Audio',
		'midi': 'MIDI Audio',
		'mkv': 'MKV Video',
		'mov': 'QuickTime Movie',
		'mp3': 'MP3 Audio',
		'mpeg': 'MPEG Movie',
		'mpg': 'MPEG Movie',
		'mrw': 'Raw',
		'msi': 'MS Installer',
		'nb': 'Mathematica',
		'numbers': 'Numbers',
		'nef': 'RAW',
		'obj': 'Wavefront',
		'ods': 'Spreadsheet',
		'odt': 'Text',
		'otf': 'OpenType Font',
		'ots': 'Spreadsheet',
		'orf': 'RAW',
		'pages': 'Pages Doc',
		'pcast': 'Podcast',
		'pdb': 'Database',
		'pdf': 'PDF',
		'pef': 'RAW',
		'php': 'PHP',
		'php3': 'PHP',
		'php4': 'PHP',
		'php5': 'PHP',
		'phtml': 'PHTML Web',
		'pl': 'Perl Script',
		'pls': 'Audio Playlist',
		'png': 'PNG',
		'ppj': 'Adobe Premiere',
		'pps': 'MS PowerPoint',
		'ppt': 'MS PowerPoint',
		'pptx': 'MS PowerPoint',
		'prproj': 'Adobe Premiere',
		'ps': 'PostScript',
		'psb': 'Photoshop',
		'psd': 'Photoshop',
		'py': 'Python Script',
		'ra': 'Real Audio',
		'ram': 'Real Audio',
		'rar': 'RAR Compressed',
		'rm': 'Real Media',
		'rtf': 'Rich Text',
		'rw2': 'RAW',
		'rwl': 'RAW',
		'sh': 'Bash Shell',
		'shtml': 'Server HTML',
		'sitx': 'X Compressed',
		'sql': 'SQL Database',
		'srf': 'Sony RAW',
		'srt': 'Subtitle',
		'svg': 'Vector',
		'svgz': 'Vector',
		'swf': 'Flash Movie',
		'tar': 'Archive',
		'tbz': 'Compressed',
		'tga': 'Targa Graphic',
		'tgz': 'Compressed',
		'tif': 'TIF',
		'tiff': 'TIFF',
		'torrent': 'Torrent',
		'ttf': 'TrueType Font',
		'txt': 'Text',
		'vcf': 'vCard',
		'wav': 'Wave Audio',
		'webm': 'WebM Video',
		'wma': 'WM Audio',
		'wmv': 'WM Video',
		'wpd': 'WordPerfect',
		'wps': 'MS Works',
		'xhtml': 'XHTML Web',
		'xlr': 'MS Works',
		'xls': 'MS Excel',
		'xlsx': 'MS Excel',
		'xlt': 'MS Excel',
		'xltm': 'MS Excel',
		'xml': 'XML',
		'zip': 'ZIP Archive',
		'mp4': 'MP4 Video'
	};

	self._mimeArray = [
		{m: 'audio/x-caf', e: 'caf'},
		{m: 'application/andrew-inset', e: 'ez'},
		{m: 'application/applixware', e: 'aw'},
		{m: 'application/atom+xml', e: 'atom'},
		{m: 'application/atomcat+xml', e: 'atomcat'},
		{m: 'application/atomsvc+xml', e: 'atomsvc'},
		{m: 'application/ccxml+xml', e: 'ccxml'},
		{m: 'application/cu-seeme', e: 'cu'},
		{m: 'application/davmount+xml', e: 'davmount'},
		{m: 'application/ecmascript', e: 'ecma'},
		{m: 'application/emma+xml', e: 'emma'},
		{m: 'application/epub+zip', e: 'epub'},
		{m: 'application/font-tdpfr', e: 'pfr'},
		{m: 'application/hyperstudio', e: 'stk'},
		{m: 'application/java-archive', e: 'jar'},
		{m: 'application/java-serialized-object', e: 'ser'},
		{m: 'application/java-vm', e: 'class'},
		{m: 'application/javascript', e: 'js'},
		{m: 'application/json', e: 'json'},
		{m: 'application/lost+xml', e: 'lostxml'},
		{m: 'application/mac-binhex40', e: 'hqx'},
		{m: 'application/mac-compactpro', e: 'cpt'},
		{m: 'application/marc', e: 'mrc'},
		{m: 'application/mathematica', e: 'ma nb mb'},
		{m: 'application/mathml+xml', e: 'mathml'},
		{m: 'application/mbox', e: 'mbox'},
		{m: 'application/mediaservercontrol+xml', e: 'mscml'},
		{m: 'application/mp4', e: 'mp4s'},
		{m: 'application/msword', e: 'doc dot'},
		{m: 'application/mxf', e: 'mxf'},
		{m: 'application/oda', e: 'oda'},
		{m: 'application/oebps-package+xml', e: 'opf'},
		{m: 'application/ogg', e: 'ogx'},
		{m: 'application/onenote', e: 'onetoc onetoc2 onetmp onepkg'},
		{m: 'application/patch-ops-error+xml', e: 'xer'},
		{m: 'application/pdf', e: 'pdf'},
		{m: 'application/pgp-encrypted', e: 'pgp'},
		{m: 'application/pgp-signature', e: 'asc sig'},
		{m: 'application/pics-rules', e: 'prf'},
		{m: 'application/pkcs10', e: 'p10'},
		{m: 'application/pkcs7-mime', e: 'p7m p7c'},
		{m: 'application/pkcs7-signature', e: 'p7s'},
		{m: 'application/pkix-cert', e: 'cer'},
		{m: 'application/pkix-crl', e: 'crl'},
		{m: 'application/pkix-pkipath', e: 'pkipath'},
		{m: 'application/pkixcmp', e: 'pki'},
		{m: 'application/pls+xml', e: 'pls'},
		{m: 'application/postscript', e: 'ai eps ps'},
		{m: 'application/prs.cww', e: 'cww'},
		{m: 'application/rdf+xml', e: 'rdf'},
		{m: 'application/reginfo+xml', e: 'rif'},
		{m: 'application/relax-ng-compact-syntax', e: 'rnc'},
		{m: 'application/resource-lists+xml', e: 'rl'},
		{m: 'application/resource-lists-diff+xml', e: 'rld'},
		{m: 'application/rls-services+xml', e: 'rs'},
		{m: 'application/rsd+xml', e: 'rsd'},
		{m: 'application/rss+xml', e: 'rss'},
		{m: 'application/rtf', e: 'rtf'},
		{m: 'application/sbml+xml', e: 'sbml'},
		{m: 'application/scvp-cv-request', e: 'scq'},
		{m: 'application/scvp-cv-response', e: 'scs'},
		{m: 'application/scvp-vp-request', e: 'spq'},
		{m: 'application/scvp-vp-response', e: 'spp'},
		{m: 'application/sdp', e: 'sdp'},
		{m: 'application/set-payment-initiation', e: 'setpay'},
		{m: 'application/set-registration-initiation', e: 'setreg'},
		{m: 'application/shf+xml', e: 'shf'},
		{m: 'application/smil+xml', e: 'smi smil'},
		{m: 'application/sparql-query', e: 'rq'},
		{m: 'application/sparql-results+xml', e: 'srx'},
		{m: 'application/srgs', e: 'gram'},
		{m: 'application/srgs+xml', e: 'grxml'},
		{m: 'application/ssml+xml', e: 'ssml'},
		{m: 'application/vnd.3gpp.pic-bw-large', e: 'plb'},
		{m: 'application/vnd.3gpp.pic-bw-small', e: 'psb'},
		{m: 'application/vnd.3gpp.pic-bw-var', e: 'pvb'},
		{m: 'application/vnd.3gpp2.tcap', e: 'tcap'},
		{m: 'application/vnd.3m.post-it-notes', e: 'pwn'},
		{m: 'application/vnd.accpac.simply.aso', e: 'aso'},
		{m: 'application/vnd.accpac.simply.imp', e: 'imp'},
		{m: 'application/vnd.acucobol', e: 'acu'},
		{m: 'application/vnd.acucorp', e: 'atc acutc'},
		{m: 'application/vnd.adobe.air-application-installer-package+zip', e: 'air'},
		{m: 'application/vnd.adobe.xdp+xml', e: 'xdp'},
		{m: 'application/vnd.adobe.xfdf', e: 'xfdf'},
		{m: 'application/vnd.airzip.filesecure.azf', e: 'azf'},
		{m: 'application/vnd.airzip.filesecure.azs', e: 'azs'},
		{m: 'application/vnd.amazon.ebook', e: 'azw'},
		{m: 'application/vnd.americandynamics.acc', e: 'acc'},
		{m: 'application/vnd.amiga.ami', e: 'ami'},
		{m: 'application/vnd.android.package-archive', e: 'apk'},
		{m: 'application/vnd.anser-web-certificate-issue-initiation', e: 'cii'},
		{m: 'application/vnd.anser-web-funds-transfer-initiation', e: 'fti'},
		{m: 'application/vnd.antix.game-component', e: 'atx'},
		{m: 'application/vnd.apple.installer+xml', e: 'mpkg'},
		{m: 'application/vnd.arastra.swi', e: 'swi'},
		{m: 'application/vnd.audiograph', e: 'aep'},
		{m: 'application/vnd.blueice.multipass', e: 'mpm'},
		{m: 'application/vnd.bmi', e: 'bmi'},
		{m: 'application/vnd.businessobjects', e: 'rep'},
		{m: 'application/vnd.chemdraw+xml', e: 'cdxml'},
		{m: 'application/vnd.chipnuts.karaoke-mmd', e: 'mmd'},
		{m: 'application/vnd.cinderella', e: 'cdy'},
		{m: 'application/vnd.claymore', e: 'cla'},
		{m: 'application/vnd.clonk.c4group', e: 'c4g c4d c4f c4p c4u'},
		{m: 'application/vnd.commonspace', e: 'csp'},
		{m: 'application/vnd.contact.cmsg', e: 'cdbcmsg'},
		{m: 'application/vnd.cosmocaller', e: 'cmc'},
		{m: 'application/vnd.crick.clicker', e: 'clkx'},
		{m: 'application/vnd.crick.clicker.keyboard', e: 'clkk'},
		{m: 'application/vnd.crick.clicker.palette', e: 'clkp'},
		{m: 'application/vnd.crick.clicker.template', e: 'clkt'},
		{m: 'application/vnd.crick.clicker.wordbank', e: 'clkw'},
		{m: 'application/vnd.criticaltools.wbs+xml', e: 'wbs'},
		{m: 'application/vnd.ctc-posml', e: 'pml'},
		{m: 'application/vnd.cups-ppd', e: 'ppd'},
		{m: 'application/vnd.curl.car', e: 'car'},
		{m: 'application/vnd.curl.pcurl', e: 'pcurl'},
		{m: 'application/vnd.data-vision.rdz', e: 'rdz'},
		{m: 'application/vnd.denovo.fcselayout-link', e: 'fe_launch'},
		{m: 'application/vnd.dna', e: 'dna'},
		{m: 'application/vnd.dolby.mlp', e: 'mlp'},
		{m: 'application/vnd.dpgraph', e: 'dpg'},
		{m: 'application/vnd.dreamfactory', e: 'dfac'},
		{m: 'application/vnd.dynageo', e: 'geo'},
		{m: 'application/vnd.ecowin.chart', e: 'mag'},
		{m: 'application/vnd.enliven', e: 'nml'},
		{m: 'application/vnd.epson.esf', e: 'esf'},
		{m: 'application/vnd.epson.msf', e: 'msf'},
		{m: 'application/vnd.epson.quickanime', e: 'qam'},
		{m: 'application/vnd.epson.salt', e: 'slt'},
		{m: 'application/vnd.epson.ssf', e: 'ssf'},
		{m: 'application/vnd.eszigno3+xml', e: 'es3 et3'},
		{m: 'application/vnd.ezpix-album', e: 'ez2'},
		{m: 'application/vnd.ezpix-package', e: 'ez3'},
		{m: 'application/vnd.fdf', e: 'fdf'},
		{m: 'application/vnd.fdsn.mseed', e: 'mseed'},
		{m: 'application/vnd.fdsn.seed', e: 'seed dataless'},
		{m: 'application/vnd.flographit', e: 'gph'},
		{m: 'application/vnd.fluxtime.clip', e: 'ftc'},
		{m: 'application/vnd.framemaker', e: 'fm frame maker book'},
		{m: 'application/vnd.frogans.fnc', e: 'fnc'},
		{m: 'application/vnd.frogans.ltf', e: 'ltf'},
		{m: 'application/vnd.fsc.weblaunch', e: 'fsc'},
		{m: 'application/vnd.fujitsu.oasys', e: 'oas'},
		{m: 'application/vnd.fujitsu.oasys2', e: 'oa2'},
		{m: 'application/vnd.fujitsu.oasys3', e: 'oa3'},
		{m: 'application/vnd.fujitsu.oasysgp', e: 'fg5'},
		{m: 'application/vnd.fujitsu.oasysprs', e: 'bh2'},
		{m: 'application/vnd.fujixerox.ddd', e: 'ddd'},
		{m: 'application/vnd.fujixerox.docuworks', e: 'xdw'},
		{m: 'application/vnd.fujixerox.docuworks.binder', e: 'xbd'},
		{m: 'application/vnd.fuzzysheet', e: 'fzs'},
		{m: 'application/vnd.genomatix.tuxedo', e: 'txd'},
		{m: 'application/vnd.geogebra.file', e: 'ggb'},
		{m: 'application/vnd.geogebra.tool', e: 'ggt'},
		{m: 'application/vnd.geometry-explorer', e: 'gex gre'},
		{m: 'application/vnd.gmx', e: 'gmx'},
		{m: 'application/vnd.google-earth.kml+xml', e: 'kml'},
		{m: 'application/vnd.google-earth.kmz', e: 'kmz'},
		{m: 'application/vnd.grafeq', e: 'gqf gqs'},
		{m: 'application/vnd.groove-account', e: 'gac'},
		{m: 'application/vnd.groove-help', e: 'ghf'},
		{m: 'application/vnd.groove-identity-message', e: 'gim'},
		{m: 'application/vnd.groove-injector', e: 'grv'},
		{m: 'application/vnd.groove-tool-message', e: 'gtm'},
		{m: 'application/vnd.groove-tool-template', e: 'tpl'},
		{m: 'application/vnd.groove-vcard', e: 'vcg'},
		{m: 'application/vnd.handheld-entertainment+xml', e: 'zmm'},
		{m: 'application/vnd.hbci', e: 'hbci'},
		{m: 'application/vnd.hhe.lesson-player', e: 'les'},
		{m: 'application/vnd.hp-hpgl', e: 'hpgl'},
		{m: 'application/vnd.hp-hpid', e: 'hpid'},
		{m: 'application/vnd.hp-hps', e: 'hps'},
		{m: 'application/vnd.hp-jlyt', e: 'jlt'},
		{m: 'application/vnd.hp-pcl', e: 'pcl'},
		{m: 'application/vnd.hp-pclxl', e: 'pclxl'},
		{m: 'application/vnd.hydrostatix.sof-data', e: 'sfd-hdstx'},
		{m: 'application/vnd.hzn-3d-crossword', e: 'x3d'},
		{m: 'application/vnd.ibm.minipay', e: 'mpy'},
		{m: 'application/vnd.ibm.modcap', e: 'afp listafp list3820'},
		{m: 'application/vnd.ibm.rights-management', e: 'irm'},
		{m: 'application/vnd.ibm.secure-container', e: 'sc'},
		{m: 'application/vnd.iccprofile', e: 'icc icm'},
		{m: 'application/vnd.igloader', e: 'igl'},
		{m: 'application/vnd.immervision-ivp', e: 'ivp'},
		{m: 'application/vnd.immervision-ivu', e: 'ivu'},
		{m: 'application/vnd.intercon.formnet', e: 'xpw xpx'},
		{m: 'application/vnd.intu.qbo', e: 'qbo'},
		{m: 'application/vnd.intu.qfx', e: 'qfx'},
		{m: 'application/vnd.ipunplugged.rcprofile', e: 'rcprofile'},
		{m: 'application/vnd.irepository.package+xml', e: 'irp'},
		{m: 'application/vnd.is-xpr', e: 'xpr'},
		{m: 'application/vnd.jam', e: 'jam'},
		{m: 'application/vnd.jcp.javame.midlet-rms', e: 'rms'},
		{m: 'application/vnd.jisp', e: 'jisp'},
		{m: 'application/vnd.joost.joda-archive', e: 'joda'},
		{m: 'application/vnd.kahootz', e: 'ktz ktr'},
		{m: 'application/vnd.kde.karbon', e: 'karbon'},
		{m: 'application/vnd.kde.kchart', e: 'chrt'},
		{m: 'application/vnd.kde.kformula', e: 'kfo'},
		{m: 'application/vnd.kde.kivio', e: 'flw'},
		{m: 'application/vnd.kde.kontour', e: 'kon'},
		{m: 'application/vnd.kde.kpresenter', e: 'kpr kpt'},
		{m: 'application/vnd.kde.kspread', e: 'ksp'},
		{m: 'application/vnd.kde.kword', e: 'kwd kwt'},
		{m: 'application/vnd.kenameaapp', e: 'htke'},
		{m: 'application/vnd.kidspiration', e: 'kia'},
		{m: 'application/vnd.kinar', e: 'kne knp'},
		{m: 'application/vnd.koan', e: 'skp skd skt skm'},
		{m: 'application/vnd.kodak-descriptor', e: 'sse'},
		{m: 'application/vnd.llamagraphics.life-balance.desktop', e: 'lbd'},
		{m: 'application/vnd.llamagraphics.life-balance.exchange+xml', e: 'lbe'},
		{m: 'application/vnd.lotus-1-2-3', e: '123'},
		{m: 'application/vnd.lotus-approach', e: 'apr'},
		{m: 'application/vnd.lotus-freelance', e: 'pre'},
		{m: 'application/vnd.lotus-notes', e: 'nsf'},
		{m: 'application/vnd.lotus-organizer', e: 'org'},
		{m: 'application/vnd.lotus-screencam', e: 'scm'},
		{m: 'application/vnd.lotus-wordpro', e: 'lwp'},
		{m: 'application/vnd.macports.portpkg', e: 'portpkg'},
		{m: 'application/vnd.mcd', e: 'mcd'},
		{m: 'application/vnd.medcalcdata', e: 'mc1'},
		{m: 'application/vnd.mediastation.cdkey', e: 'cdkey'},
		{m: 'application/vnd.mfer', e: 'mwf'},
		{m: 'application/vnd.mfmp', e: 'mfm'},
		{m: 'application/vnd.micrografx.flo', e: 'flo'},
		{m: 'application/vnd.micrografx.igx', e: 'igx'},
		{m: 'application/vnd.mif', e: 'mif'},
		{m: 'application/vnd.mobius.daf', e: 'daf'},
		{m: 'application/vnd.mobius.dis', e: 'dis'},
		{m: 'application/vnd.mobius.mbk', e: 'mbk'},
		{m: 'application/vnd.mobius.mqy', e: 'mqy'},
		{m: 'application/vnd.mobius.msl', e: 'msl'},
		{m: 'application/vnd.mobius.plc', e: 'plc'},
		{m: 'application/vnd.mobius.txf', e: 'txf'},
		{m: 'application/vnd.mophun.application', e: 'mpn'},
		{m: 'application/vnd.mophun.certificate', e: 'mpc'},
		{m: 'application/vnd.mozilla.xul+xml', e: 'xul'},
		{m: 'application/vnd.ms-artgalry', e: 'cil'},
		{m: 'application/vnd.ms-cab-compressed', e: 'cab'},
		{m: 'application/vnd.ms-excel', e: 'xls xlm xla xlc xlt xlw'},
		{m: 'application/vnd.ms-excel.addin.macroenabled.12', e: 'xlam'},
		{m: 'application/vnd.ms-excel.sheet.binary.macroenabled.12', e: 'xlsb'},
		{m: 'application/vnd.ms-excel.sheet.macroenabled.12', e: 'xlsm'},
		{m: 'application/vnd.ms-excel.template.macroenabled.12', e: 'xltm'},
		{m: 'application/vnd.ms-fontobject', e: 'eot'},
		{m: 'application/vnd.ms-htmlhelp', e: 'chm'},
		{m: 'application/vnd.ms-ims', e: 'ims'},
		{m: 'application/vnd.ms-lrm', e: 'lrm'},
		{m: 'application/vnd.ms-pki.seccat', e: 'cat'},
		{m: 'application/vnd.ms-pki.stl', e: 'stl'},
		{m: 'application/vnd.ms-powerpoint', e: 'ppt pps pot'},
		{m: 'application/vnd.ms-powerpoint.addin.macroenabled.12', e: 'ppam'},
		{m: 'application/vnd.ms-powerpoint.presentation.macroenabled.12', e: 'pptm'},
		{m: 'application/vnd.ms-powerpoint.slide.macroenabled.12', e: 'sldm'},
		{m: 'application/vnd.ms-powerpoint.slideshow.macroenabled.12', e: 'ppsm'},
		{m: 'application/vnd.ms-powerpoint.template.macroenabled.12', e: 'potm'},
		{m: 'application/vnd.ms-project', e: 'mpp mpt'},
		{m: 'application/vnd.ms-word.document.macroenabled.12', e: 'docm'},
		{m: 'application/vnd.ms-word.template.macroenabled.12', e: 'dotm'},
		{m: 'application/vnd.ms-works', e: 'wps wks wcm wdb'},
		{m: 'application/vnd.ms-wpl', e: 'wpl'},
		{m: 'application/vnd.ms-xpsdocument', e: 'xps'},
		{m: 'application/vnd.mseq', e: 'mseq'},
		{m: 'application/vnd.musician', e: 'mus'},
		{m: 'application/vnd.muvee.style', e: 'msty'},
		{m: 'application/vnd.neurolanguage.nlu', e: 'nlu'},
		{m: 'application/vnd.noblenet-directory', e: 'nnd'},
		{m: 'application/vnd.noblenet-sealer', e: 'nns'},
		{m: 'application/vnd.noblenet-web', e: 'nnw'},
		{m: 'application/vnd.nokia.n-gage.data', e: 'ngdat'},
		{m: 'application/vnd.nokia.n-gage.symbian.install', e: 'n-gage'},
		{m: 'application/vnd.nokia.radio-preset', e: 'rpst'},
		{m: 'application/vnd.nokia.radio-presets', e: 'rpss'},
		{m: 'application/vnd.novadigm.edm', e: 'edm'},
		{m: 'application/vnd.novadigm.edx', e: 'edx'},
		{m: 'application/vnd.novadigm.ext', e: 'ext'},
		{m: 'application/vnd.oasis.opendocument.chart', e: 'odc'},
		{m: 'application/vnd.oasis.opendocument.chart-template', e: 'otc'},
		{m: 'application/vnd.oasis.opendocument.database', e: 'odb'},
		{m: 'application/vnd.oasis.opendocument.formula', e: 'odf'},
		{m: 'application/vnd.oasis.opendocument.formula-template', e: 'odft'},
		{m: 'application/vnd.oasis.opendocument.graphics', e: 'odg'},
		{m: 'application/vnd.oasis.opendocument.graphics-template', e: 'otg'},
		{m: 'application/vnd.oasis.opendocument.image', e: 'odi'},
		{m: 'application/vnd.oasis.opendocument.image-template', e: 'oti'},
		{m: 'application/vnd.oasis.opendocument.presentation', e: 'odp'},
		{m: 'application/vnd.oasis.opendocument.spreadsheet', e: 'ods'},
		{m: 'application/vnd.oasis.opendocument.spreadsheet-template', e: 'ots'},
		{m: 'application/vnd.oasis.opendocument.text', e: 'odt'},
		{m: 'application/vnd.oasis.opendocument.text-master', e: 'otm'},
		{m: 'application/vnd.oasis.opendocument.text-template', e: 'ott'},
		{m: 'application/vnd.oasis.opendocument.text-web', e: 'oth'},
		{m: 'application/vnd.olpc-sugar', e: 'xo'},
		{m: 'application/vnd.oma.dd2+xml', e: 'dd2'},
		{m: 'application/vnd.openofficeorg.extension', e: 'oxt'},
		{m: 'application/vnd.openxmlformats-officedocument.presentationml.presentation', e: 'pptx'},
		{m: 'application/vnd.openxmlformats-officedocument.presentationml.slide', e: 'sldx'},
		{m: 'application/vnd.openxmlformats-officedocument.presentationml.slideshow', e: 'ppsx'},
		{m: 'application/vnd.openxmlformats-officedocument.presentationml.template', e: 'potx'},
		{m: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', e: 'xlsx'},
		{m: 'application/vnd.openxmlformats-officedocument.spreadsheetml.template', e: 'xltx'},
		{m: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', e: 'docx'},
		{m: 'application/vnd.openxmlformats-officedocument.wordprocessingml.template', e: 'dotx'},
		{m: 'application/vnd.osgi.dp', e: 'dp'},
		{m: 'application/vnd.palm', e: 'pdb pqa oprc'},
		{m: 'application/vnd.pg.format', e: 'str'},
		{m: 'application/vnd.pg.osasli', e: 'ei6'},
		{m: 'application/vnd.picsel', e: 'efif'},
		{m: 'application/vnd.pocketlearn', e: 'plf'},
		{m: 'application/vnd.powerbuilder6', e: 'pbd'},
		{m: 'application/vnd.previewsystems.box', e: 'box'},
		{m: 'application/vnd.proteus.magazine', e: 'mgz'},
		{m: 'application/vnd.publishare-delta-tree', e: 'qps'},
		{m: 'application/vnd.pvi.ptid1', e: 'ptid'},
		{m: 'application/vnd.quark.quarkxpress', e: 'qxd qxt qwd qwt qxl qxb'},
		{m: 'application/vnd.recordare.musicxml', e: 'mxl'},
		{m: 'application/vnd.recordare.musicxml+xml', e: 'musicxml'},
		{m: 'application/vnd.rim.cod', e: 'cod'},
		{m: 'application/vnd.rn-realmedia', e: 'rm'},
		{m: 'application/vnd.route66.link66+xml', e: 'link66'},
		{m: 'application/vnd.seemail', e: 'see'},
		{m: 'application/vnd.sema', e: 'sema'},
		{m: 'application/vnd.semd', e: 'semd'},
		{m: 'application/vnd.semf', e: 'semf'},
		{m: 'application/vnd.shana.informed.formdata', e: 'ifm'},
		{m: 'application/vnd.shana.informed.formtemplate', e: 'itp'},
		{m: 'application/vnd.shana.informed.interchange', e: 'iif'},
		{m: 'application/vnd.shana.informed.package', e: 'ipk'},
		{m: 'application/vnd.simtech-mindmapper', e: 'twd twds'},
		{m: 'application/vnd.smaf', e: 'mmf'},
		{m: 'application/vnd.smart.teacher', e: 'teacher'},
		{m: 'application/vnd.solent.sdkm+xml', e: 'sdkm sdkd'},
		{m: 'application/vnd.spotfire.dxp', e: 'dxp'},
		{m: 'application/vnd.spotfire.sfs', e: 'sfs'},
		{m: 'application/vnd.stardivision.calc', e: 'sdc'},
		{m: 'application/vnd.stardivision.draw', e: 'sda'},
		{m: 'application/vnd.stardivision.impress', e: 'sdd'},
		{m: 'application/vnd.stardivision.math', e: 'smf'},
		{m: 'application/vnd.stardivision.writer', e: 'sdw'},
		{m: 'application/vnd.stardivision.writer', e: 'vor'},
		{m: 'application/vnd.stardivision.writer-global', e: 'sgl'},
		{m: 'application/vnd.sun.xml.calc', e: 'sxc'},
		{m: 'application/vnd.sun.xml.calc.template', e: 'stc'},
		{m: 'application/vnd.sun.xml.draw', e: 'sxd'},
		{m: 'application/vnd.sun.xml.draw.template', e: 'std'},
		{m: 'application/vnd.sun.xml.impress', e: 'sxi'},
		{m: 'application/vnd.sun.xml.impress.template', e: 'sti'},
		{m: 'application/vnd.sun.xml.math', e: 'sxm'},
		{m: 'application/vnd.sun.xml.writer', e: 'sxw'},
		{m: 'application/vnd.sun.xml.writer.global', e: 'sxg'},
		{m: 'application/vnd.sun.xml.writer.template', e: 'stw'},
		{m: 'application/vnd.sus-calendar', e: 'sus susp'},
		{m: 'application/vnd.svd', e: 'svd'},
		{m: 'application/vnd.symbian.install', e: 'sis sisx'},
		{m: 'application/vnd.syncml+xml', e: 'xsm'},
		{m: 'application/vnd.syncml.dm+wbxml', e: 'bdm'},
		{m: 'application/vnd.syncml.dm+xml', e: 'xdm'},
		{m: 'application/vnd.tao.intent-module-archive', e: 'tao'},
		{m: 'application/vnd.tmobile-livetv', e: 'tmo'},
		{m: 'application/vnd.trid.tpt', e: 'tpt'},
		{m: 'application/vnd.triscape.mxs', e: 'mxs'},
		{m: 'application/vnd.trueapp', e: 'tra'},
		{m: 'application/vnd.ufdl', e: 'ufd ufdl'},
		{m: 'application/vnd.uiq.theme', e: 'utz'},
		{m: 'application/vnd.umajin', e: 'umj'},
		{m: 'application/vnd.unity', e: 'unityweb'},
		{m: 'application/vnd.uoml+xml', e: 'uoml'},
		{m: 'application/vnd.vcx', e: 'vcx'},
		{m: 'application/vnd.visio', e: 'vsd vst vss vsw'},
		{m: 'application/vnd.visionary', e: 'vis'},
		{m: 'application/vnd.vsf', e: 'vsf'},
		{m: 'application/vnd.wap.wbxml', e: 'wbxml'},
		{m: 'application/vnd.wap.wmlc', e: 'wmlc'},
		{m: 'application/vnd.wap.wmlscriptc', e: 'wmlsc'},
		{m: 'application/vnd.webturbo', e: 'wtb'},
		{m: 'application/vnd.wordperfect', e: 'wpd'},
		{m: 'application/vnd.wqd', e: 'wqd'},
		{m: 'application/vnd.wt.stf', e: 'stf'},
		{m: 'application/vnd.xara', e: 'xar'},
		{m: 'application/vnd.xfdl', e: 'xfdl'},
		{m: 'application/vnd.yamaha.hv-dic', e: 'hvd'},
		{m: 'application/vnd.yamaha.hv-script', e: 'hvs'},
		{m: 'application/vnd.yamaha.hv-voice', e: 'hvp'},
		{m: 'application/vnd.yamaha.openscoreformat', e: 'osf'},
		{m: 'application/vnd.yamaha.openscoreformat.osfpvg+xml', e: 'osfpvg'},
		{m: 'application/vnd.yamaha.smaf-audio', e: 'saf'},
		{m: 'application/vnd.yamaha.smaf-phrase', e: 'spf'},
		{m: 'application/vnd.yellowriver-custom-menu', e: 'cmp'},
		{m: 'application/vnd.zul', e: 'zir zirz'},
		{m: 'application/vnd.zzazz.deck+xml', e: 'zaz'},
		{m: 'application/voicexml+xml', e: 'vxml'},
		{m: 'application/winhlp', e: 'hlp'},
		{m: 'application/wsdl+xml', e: 'wsdl'},
		{m: 'application/wspolicy+xml', e: 'wspolicy'},
		{m: 'application/x-abiword', e: 'abw'},
		{m: 'application/x-ace-compressed', e: 'ace'},
		{m: 'application/x-authorware-bin', e: 'aab x32 u32 vox'},
		{m: 'application/x-authorware-map', e: 'aam'},
		{m: 'application/x-authorware-seg', e: 'aas'},
		{m: 'application/x-bcpio', e: 'bcpio'},
		{m: 'application/x-bittorrent', e: 'torrent'},
		{m: 'application/x-bzip', e: 'bz'},
		{m: 'application/x-bzip2', e: 'bz2 boz'},
		{m: 'application/x-cdlink', e: 'vcd'},
		{m: 'application/x-chat', e: 'chat'},
		{m: 'application/x-chess-pgn', e: 'pgn'},
		{m: 'application/x-cpio', e: 'cpio'},
		{m: 'application/x-csh', e: 'csh'},
		{m: 'application/x-debian-package', e: 'deb udeb'},
		{m: 'application/x-director', e: 'dir dcr dxr cst cct cxt w3d fgd swa'},
		{m: 'application/x-doom', e: 'wad'},
		{m: 'application/x-dtbncx+xml', e: 'ncx'},
		{m: 'application/x-dtbook+xml', e: 'dtb'},
		{m: 'application/x-dtbresource+xml', e: 'res'},
		{m: 'application/x-dvi', e: 'dvi'},
		{m: 'application/x-font-bdf', e: 'bdf'},
		{m: 'application/x-font-ghostscript', e: 'gsf'},
		{m: 'application/x-font-linux-psf', e: 'psf'},
		{m: 'application/x-font-otf', e: 'otf'},
		{m: 'application/x-font-pcf', e: 'pcf'},
		{m: 'application/x-font-snf', e: 'snf'},
		{m: 'application/x-font-ttf', e: 'ttf ttc'},
		{m: 'application/x-font-type1', e: 'pfa pfb pfm afm'},
		{m: 'application/x-futuresplash', e: 'spl'},
		{m: 'application/x-gnumeric', e: 'gnumeric'},
		{m: 'application/x-gtar', e: 'gtar'},
		{m: 'application/x-hdf', e: 'hdf'},
		{m: 'application/x-java-jnlp-file', e: 'jnlp'},
		{m: 'application/x-latex', e: 'latex'},
		{m: 'application/x-mobipocket-ebook', e: 'prc mobi'},
		{m: 'application/x-ms-application', e: 'application'},
		{m: 'application/x-ms-wmd', e: 'wmd'},
		{m: 'application/x-ms-wmz', e: 'wmz'},
		{m: 'application/x-ms-xbap', e: 'xbap'},
		{m: 'application/x-msaccess', e: 'mdb'},
		{m: 'application/x-msbinder', e: 'obd'},
		{m: 'application/x-mscardfile', e: 'crd'},
		{m: 'application/x-msclip', e: 'clp'},
		{m: 'application/x-msdownload', e: 'exe dll com bat msi'},
		{m: 'application/x-msmediaview', e: 'mvb m13 m14'},
		{m: 'application/x-msmetafile', e: 'wmf'},
		{m: 'application/x-msmoney', e: 'mny'},
		{m: 'application/x-mspublisher', e: 'pub'},
		{m: 'application/x-msschedule', e: 'scd'},
		{m: 'application/x-msterminal', e: 'trm'},
		{m: 'application/x-mswrite', e: 'wri'},
		{m: 'application/x-netcdf', e: 'nc cdf'},
		{m: 'application/x-pkcs12', e: 'p12 pfx'},
		{m: 'application/x-pkcs7-certificates', e: 'p7b spc'},
		{m: 'application/x-pkcs7-certreqresp', e: 'p7r'},
		{m: 'application/x-rar-compressed', e: 'rar'},
		{m: 'application/x-sh', e: 'sh'},
		{m: 'application/x-shar', e: 'shar'},
		{m: 'application/x-shockwave-flash', e: 'swf'},
		{m: 'application/x-silverlight-app', e: 'xap'},
		{m: 'application/x-stuffit', e: 'sit'},
		{m: 'application/x-stuffitx', e: 'sitx'},
		{m: 'application/x-sv4cpio', e: 'sv4cpio'},
		{m: 'application/x-sv4crc', e: 'sv4crc'},
		{m: 'application/x-tar', e: 'tar'},
		{m: 'application/x-tcl', e: 'tcl'},
		{m: 'application/x-tex', e: 'tex'},
		{m: 'application/x-tex-tfm', e: 'tfm'},
		{m: 'application/x-texinfo', e: 'texinfo texi'},
		{m: 'application/x-ustar', e: 'ustar'},
		{m: 'application/x-wais-source', e: 'src'},
		{m: 'application/x-x509-ca-cert', e: 'der crt'},
		{m: 'application/x-xfig', e: 'fig'},
		{m: 'application/x-xpinstall', e: 'xpi'},
		{m: 'application/xenc+xml', e: 'xenc'},
		{m: 'application/xhtml+xml', e: 'xhtml xht'},
		{m: 'application/xml', e: 'xml xsl'},
		{m: 'application/xml-dtd', e: 'dtd'},
		{m: 'application/xop+xml', e: 'xop'},
		{m: 'application/xslt+xml', e: 'xslt'},
		{m: 'application/xspf+xml', e: 'xspf'},
		{m: 'application/xv+xml', e: 'mxml xhvml xvml xvm'},
		{m: 'application/zip', e: 'zip'},
		{m: 'audio/adpcm', e: 'adp'},
		{m: 'audio/basic', e: 'au snd'},
		{m: 'audio/midi', e: 'mid midi kar rmi'},
		{m: 'audio/mp4', e: 'mp4a'},
		{m: 'audio/mp4a-latm', e: 'm4a m4p'},
		{m: 'audio/mpeg', e: 'mpga mp2 mp2a mp3 m2a m3a'},
		{m: 'audio/ogg', e: 'oga ogg spx'},
		{m: 'audio/vnd.digital-winds', e: 'eol'},
		{m: 'audio/vnd.dts', e: 'dts'},
		{m: 'audio/vnd.dts.hd', e: 'dtshd'},
		{m: 'audio/vnd.lucent.voice', e: 'lvp'},
		{m: 'audio/vnd.ms-playready.media.pya', e: 'pya'},
		{m: 'audio/vnd.nuera.ecelp4800', e: 'ecelp4800'},
		{m: 'audio/vnd.nuera.ecelp7470', e: 'ecelp7470'},
		{m: 'audio/vnd.nuera.ecelp9600', e: 'ecelp9600'},
		{m: 'audio/x-aac', e: 'aac'},
		{m: 'audio/x-aiff', e: 'aif aiff aifc'},
		{m: 'audio/x-mpegurl', e: 'm3u'},
		{m: 'audio/x-ms-wax', e: 'wax'},
		{m: 'audio/x-ms-wma', e: 'wma'},
		{m: 'audio/x-pn-realaudio', e: 'ram ra'},
		{m: 'audio/x-pn-realaudio-plugin', e: 'rmp'},
		{m: 'audio/x-wav', e: 'wav'},
		{m: 'chemical/x-cdx', e: 'cdx'},
		{m: 'chemical/x-cif', e: 'cif'},
		{m: 'chemical/x-cmdf', e: 'cmdf'},
		{m: 'chemical/x-cml', e: 'cml'},
		{m: 'chemical/x-csml', e: 'csml'},
		{m: 'chemical/x-xyz', e: 'xyz'},
		{m: 'image/bmp', e: 'bmp'},
		{m: 'image/cgm', e: 'cgm'},
		{m: 'image/g3fax', e: 'g3'},
		{m: 'image/gif', e: 'gif'},
		{m: 'image/ief', e: 'ief'},
		{m: 'image/jp2', e: 'jp2'},
		{m: 'image/jpeg', e: 'jpeg jpg jpe'},
		{m: 'image/pict', e: 'pict pic pct'},
		{m: 'image/png', e: 'png'},
		{m: 'image/prs.btif', e: 'btif'},
		{m: 'image/svg+xml', e: 'svg svgz'},
		{m: 'image/tiff', e: 'tiff tif'},
		{m: 'image/vnd.adobe.photoshop', e: 'psd'},
		{m: 'image/vnd.djvu', e: 'djvu djv'},
		{m: 'image/vnd.dwg', e: 'dwg'},
		{m: 'image/vnd.dxf', e: 'dxf'},
		{m: 'image/vnd.fastbidsheet', e: 'fbs'},
		{m: 'image/vnd.fpx', e: 'fpx'},
		{m: 'image/vnd.fst', e: 'fst'},
		{m: 'image/vnd.fujixerox.edmics-mmr', e: 'mmr'},
		{m: 'image/vnd.fujixerox.edmics-rlc', e: 'rlc'},
		{m: 'image/vnd.ms-modi', e: 'mdi'},
		{m: 'image/vnd.net-fpx', e: 'npx'},
		{m: 'image/vnd.wap.wbmp', e: 'wbmp'},
		{m: 'image/vnd.xiff', e: 'xif'},
		{m: 'image/x-cmu-raster', e: 'ras'},
		{m: 'image/x-cmx', e: 'cmx'},
		{m: 'image/x-freehand', e: 'fh fhc fh4 fh5 fh7'},
		{m: 'image/x-icon', e: 'ico'},
		{m: 'image/x-macpaint', e: 'pntg pnt mac'},
		{m: 'image/x-pcx', e: 'pcx'},
		{m: 'image/x-portable-anymap', e: 'pnm'},
		{m: 'image/x-portable-bitmap', e: 'pbm'},
		{m: 'image/x-portable-graymap', e: 'pgm'},
		{m: 'image/x-portable-pixmap', e: 'ppm'},
		{m: 'image/x-quicktime', e: 'qtif qti'},
		{m: 'image/x-rgb', e: 'rgb'},
		{m: 'image/x-xbitmap', e: 'xbm'},
		{m: 'image/x-xpixmap', e: 'xpm'},
		{m: 'image/x-xwindowdump', e: 'xwd'},
		{m: 'message/rfc822', e: 'eml mime'},
		{m: 'model/iges', e: 'igs iges'},
		{m: 'model/mesh', e: 'msh mesh silo'},
		{m: 'model/vnd.dwf', e: 'dwf'},
		{m: 'model/vnd.gdl', e: 'gdl'},
		{m: 'model/vnd.gtw', e: 'gtw'},
		{m: 'model/vnd.mts', e: 'mts'},
		{m: 'model/vnd.vtu', e: 'vtu'},
		{m: 'model/vrml', e: 'wrl vrml'},
		{m: 'text/calendar', e: 'ics ifb'},
		{m: 'text/css', e: 'css'},
		{m: 'text/csv', e: 'csv'},
		{m: 'text/html', e: 'html htm'},
		{m: 'text/plain', e: 'txt text conf def list log in'},
		{m: 'text/prs.lines.tag', e: 'dsc'},
		{m: 'text/richtext', e: 'rtx'},
		{m: 'text/sgml', e: 'sgml sgm'},
		{m: 'text/tab-separated-values', e: 'tsv'},
		{m: 'text/troff', e: 't tr roff man me ms'},
		{m: 'text/uri-list', e: 'uri uris urls'},
		{m: 'text/vnd.curl', e: 'curl'},
		{m: 'text/vnd.curl.dcurl', e: 'dcurl'},
		{m: 'text/vnd.curl.scurl', e: 'scurl'},
		{m: 'text/vnd.curl.mcurl', e: 'mcurl'},
		{m: 'text/vnd.fly', e: 'fly'},
		{m: 'text/vnd.fmi.flexstor', e: 'flx'},
		{m: 'text/vnd.graphviz', e: 'gv'},
		{m: 'text/vnd.in3d.3dml', e: '3dml'},
		{m: 'text/vnd.in3d.spot', e: 'spot'},
		{m: 'text/vnd.sun.j2me.app-descriptor', e: 'jad'},
		{m: 'text/vnd.wap.wml', e: 'wml'},
		{m: 'text/vnd.wap.wmlscript', e: 'wmls'},
		{m: 'text/x-asm', e: 's asm'},
		{m: 'text/x-c', e: 'c cc cxx cpp h hh dic'},
		{m: 'text/x-fortran', e: 'f for f77 f90'},
		{m: 'text/x-pascal', e: 'p pas'},
		{m: 'text/x-java-source', e: 'java'},
		{m: 'text/x-setext', e: 'etx'},
		{m: 'text/x-uuencode', e: 'uu'},
		{m: 'text/x-vcalendar', e: 'vcs'},
		{m: 'text/x-vcard', e: 'vcf'},
		{m: 'video/3gpp', e: '3gp'},
		{m: 'video/3gpp2', e: '3g2'},
		{m: 'video/h261', e: 'h261'},
		{m: 'video/h263', e: 'h263'},
		{m: 'video/h264', e: 'h264'},
		{m: 'video/jpeg', e: 'jpgv'},
		{m: 'video/jpm', e: 'jpm jpgm'},
		{m: 'video/mj2', e: 'mj2 mjp2'},
		{m: 'video/mp4', e: 'mp4 mp4v mpg4 m4v'},
		{m: 'video/mpeg', e: 'mpeg mpg mpe m1v m2v'},
		{m: 'video/ogg', e: 'ogv'},
		{m: 'video/quicktime', e: 'qt mov'},
		{m: 'video/vnd.fvt', e: 'fvt'},
		{m: 'video/vnd.mpegurl', e: 'mxu m4u'},
		{m: 'video/vnd.ms-playready.media.pyv', e: 'pyv'},
		{m: 'video/vnd.vivo', e: 'viv'},
		{m: 'video/x-dv', e: 'dv dif'},
		{m: 'video/x-f4v', e: 'f4v'},
		{m: 'video/x-fli', e: 'fli'},
		{m: 'video/x-flv', e: 'flv'},
		{m: 'video/x-ms-asf', e: 'asf asx'},
		{m: 'video/x-ms-wm', e: 'wm'},
		{m: 'video/x-ms-wmv', e: 'wmv'},
		{m: 'video/x-ms-wmx', e: 'wmx'},
		{m: 'video/x-ms-wvx', e: 'wvx'},
		{m: 'video/x-msvideo', e: 'avi'},
		{m: 'video/x-sgi-movie', e: 'movie'},
		{m: 'x-conference/x-cooltalk', e: 'ice'}
	];

	self._init = function(){

		var i, j, d;

		for(i in self._extTable){

			for(j in self._extTable[i][0]){

				d = self._extTable[i][1];
				if(self._extWide[self._extTable[i][0][j]]) d = self._extWide[self._extTable[i][0][j]];
				self._types[self._extTable[i][0][j]] = [i, d];

			}

		}

	};

	self.fileExt = function(fn){

		var e = fn.substr(fn.lastIndexOf('.') + 1);
		if(e === fn) e = '';
		return e.toLowerCase();	

	};

	self.fileClass = function(fn){

		var e = self.fileExt(fn) || '*';
		return self._types[e] ? self._types[e][0] : self._types['*'][0];

	};

	self.fileType = function(fn){

		var e = self.fileExt(fn) || '*';
		return self._types[e] ? self._types[e][1] : self._types['*'][1];

	};

	self.fileMimeType = function(fn){

		self._mime || self._initMimeTypes();
		var e = self.fileExt(fn) || 'e';
		return self._mime[e] ? self._mime[e] : 'application/octet-stream';

	};

	self.isVideo = function(fn){

		return self.fileMimeType(fn).match(/video/i);

	};

	self.isImage = function(fn){

		return self.fileMimeType(fn).match(/image/i);

	};

	self._initMimeTypes = function(){

		var i, j, x;
		self._mime = {};

		for(i in self._mimeArray){

			j = self._mimeArray[i].e.split(' ');
			for(x in j) self._mime[j[x]] = self._mimeArray[i].m;

		}

	};

	self._init();

}